set shell := ["zsh", "-cu"]

default:
  just --list

# up:
#   docker compose up --remove-orphans -w

# down:
#   docker compose down --remove-orphans --volumes

# build:
#   docker compose build

venv: 
  python -m venv .venv
  # Use uv package to pip install.
  # Ref: https://github.com/astral-sh/uv?tab=readme-ov-file#highlights
  source .venv/bin/activate \
    && pip install uv \
    && uv pip install -r requirements.txt

run:
  cd dagster_toy dagster dev