set shell := ["zsh", "-cu"]

default: run

run:
    @if [ $(k3d cluster list --no-headers -o json | jq '.[] | .name' | grep -q 'k3s-default')] == 0 ]; then k3d cluster create; fi

    docker build -t signal-generator -f ./Dockerfile_Signal_Generator .

clean:
    k3d cluster delete


# 49858