set shell := ["zsh", "-cu"]

# default:

data:
    cd seeds && jafgen --years 1 && cd ..

seed:
    dbt seed --profiles-dir .  # Insert Seed stuff.

test:
    dbt test --profiles-dir .  # Runs tests.
    dbt debug --profiles-dir .  # Checks configs.

run: 
    dbt run --profiles-dir .  # Runs model creation, etc.

docs:
    dbt docs generate
    dbt docs serve --port 8001
