set shell := ["zsh", "-cu"]

default:
  just --list

# Uses uv package to pip install.
# Ref: https://github.com/astral-sh/uv?tab=readme-ov-file#highlights
venv: 
  export CONDA_PREFIX="" \
    && python -m venv .venv

  # Unsure why I have to export again...
  export CONDA_PREFIX="" \
    && source .venv/bin/activate \
    && pip install uv \
    && uv pip install -r requirements.txt

# test:
#   python -m pytest --doctest-modules ./tests
data:
    cd seeds && jafgen 1 && cd ..

seed:
    dbt seed --profiles-dir .  # Insert Seed stuff.

test:
    dbt test --profiles-dir .  # Runs tests.
    dbt debug --profiles-dir .  # Checks configs.

run: 
    dbt run --profiles-dir .  # Runs model creation, etc.

docs:
    dbt docs generate
    dbt docs serve --port 8001
