set shell := ["zsh", "-cu"]

default:
  just --list

# Requires docker to be set up.
run:
  python ./glassdolls/main_game.py

up:
  docker compose up --remove-orphans -w

down:
  docker compose down --remove-orphans --volumes

build:
  docker compose build

venv: 
  python -m venv .venv
  # Use uv package to pip install.
  # Ref: https://github.com/astral-sh/uv?tab=readme-ov-file#highlights
  export CONDA_PREFIX="" \
    && source .venv/bin/activate \
    && pip install --upgrade pip \
    && pip install uv \
    && uv pip install -r requirements.txt \
    && uv pip install -r requirements-dev.txt