set shell := ["zsh", "-cu"]

default:
  just --list

create_users:
  # If you change the MB port, change it here too.
  MB_HOSTNAME=localhost MB_PORT=3000 ./create_users.sh


run:
  docker compose up
